import { notFound } from "next/navigation";
import Footer from "./components/Footer";
import Header from "./components/Header";
import { getDictionary } from "./dictionaries/dictionaries";

export async function generateMetadata({}) {
  return {
    title: "MovieBD - LWS",
    description: "Generated by create next app",
  };
}

export default async function RootLayout({ children, modal, params }) {
  const langValid = ["en", "bn"].includes(params.lang);

  if (!langValid) {
    return notFound();
  }
  const dict = await getDictionary(params.lang);
  return (
    <>
      {modal}
      <>
        <Header lang={params.lang} />
        {children}
        <Footer text={dict?.footer} />
      </>
    </>
  );
}
